// <auto-generated />
using Draw.it.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Draw.it.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209084215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Draw.it.Server.Models.Room.RoomModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<long>("HostId")
                        .HasColumnType("bigint")
                        .HasColumnName("host_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Draw.it.Server.Models.User.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_connected");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("RoomId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Draw.it.Server.Models.Room.RoomModel", b =>
                {
                    b.OwnsOne("Draw.it.Server.Models.Room.RoomSettingsModel", "Settings", b1 =>
                        {
                            b1.Property<string>("RoomModelId")
                                .HasColumnType("character varying(16)");

                            b1.Property<long>("CategoryId")
                                .HasColumnType("bigint")
                                .HasColumnName("category_id");

                            b1.Property<int>("DrawingTime")
                                .HasColumnType("integer")
                                .HasColumnName("drawing_time_seconds");

                            b1.Property<int>("NumberOfRounds")
                                .HasColumnType("integer")
                                .HasColumnName("number_of_rounds");

                            b1.Property<string>("RoomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("room_name");

                            b1.HasKey("RoomModelId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomModelId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Draw.it.Server.Models.User.UserModel", b =>
                {
                    b.HasOne("Draw.it.Server.Models.Room.RoomModel", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
